### PR TITLE
add xcode 11.4 support

### PR DESCRIPTION
**Pull request by carlosgarciapecun**
#604

### CODE REVIEW

**Comment by Urkman** [comment]
Can you please ASAP merge this PR?
So that we can update to Xcode 11.4

**Comment by mikchmie** [comment]
This duplicates #598

**Comment by jonkykong** [comment]
Thanks for you submission and sorry for the delay. I've been very busy.

**Comment by carlosypunto** [comment]
no problem, until the moment, I'm pointing to my repo

**Pull request merged**
