### PR TITLE
Upgrade project to Xcode 10.2 and Swift 5

### PR DESCRIPTION
**Pull request by stelabouras**
Applies migrations for Swift 5 under Xcode 10.2

### CODE REVIEW

**Comment by stelabouras** [comment]
@jonkykong Feel free to review and leave some feedback! 😄

**Comment by tudorpopa39** [comment]
I really need this update

**Comment by stelabouras** [comment]
Pull request has been updated to include one more fix by @Zeta611 regarding the `.podspec` file.

**Comment by Alexookah** [comment]
i really need this update

**Comment by amrangry** [comment]
how we can take this update i mean using pods?

**Comment by Zeta611** [comment]
You can add:
```
pod 'SideMenu', :git => 'https://github.com/stelabouras/SideMenu.git', :branch => 'upgrade/xcode-10.2'
```
in your Podfile, as for now.

**Comment by JamesBedford** [comment]
Please let's get this merged in! :)

**Comment by musa-almatri** [comment]
Any idea when this will be merged?

**Comment by Zeta611** [comment]
Maybe this repo is no longer maintained? The latest commit's from last year..

**Comment by Alexookah** [comment]
> Maybe this repo is no longer maintained? The latest commit's from last year..

last commit in another branch "major refactor", 17 days ago

**Comment by jonkykong** [comment]
Folks, sorry for the radio silence. I have been long working on a major refactor of this project because it has been a pain to maintain and taken way more of my time than I ever anticipated. Before I merge any pull request I make sure things are working as expected, and I've barely had the time to allocate to the refactor alone (which is in Swift 5). You should be able to update your pods to pull to this PR's branch, if it's urgent for you to be using Swift 5.

I appreciate your patience.

**Comment by borut-t** [comment]
@jonkykong that's great to hear you are working on a refactor. But I would propose that you release swift 5 compatible version and work on refactor afterward 🤷‍♂

**Comment by jonkykong** [comment]
Hi @stelabouras and everyone else, SideMenu 6.0.0 is now available which includes support for Swift 5. Please run `pod update` to get the latest source. Unfortunately there are lots of changes so you will see some deprecation warnings in your code, however the setup is still ultra simple so it should not take long to migrate.

**Pull request closed without merging**
