### PR TITLE
Compatible with Swift4

### PR DESCRIPTION
**Pull request by didisouzacosta**
Changes for compatible with swift4.

### CODE REVIEW

**Comment by jonkykong** [comment]
Hi @didisouzacosta, is this the result of going through Xcode's upgrade swift process? The only code changes I see are adding `@objc` to some of the methods, which should not be necessary. Other than that, it should only be to silence Xcode's warnings about Swift version support by upgrading the supported version.

**Comment by seeker12** [comment]
@jonkykong - there appears to be a number cocoapod related version updates, as well as Xcode 9 `@objc` warning fixes.

**Comment by tudorpopa39** [comment]
@jonkykong - I would like to know when this changes will be merged to master, now when Swift4 and Xcode 9 is officially on

**Comment by Ethandf90** [comment]
please make Swift 4 support soon, thanks!

**Comment by RamblinWreck77** [comment]
Hello, I had to make these changes as well. Please consider merging this and releasing an update.

**Comment by jonkykong** [comment]
Closing in favor of #253.

**Pull request closed without merging**
