### PR TITLE
adding delegates for animation synchronization

### PR DESCRIPTION
**Pull request by rdmrocha**

### CODE REVIEW

**Comment by jonkykong** [comment]
@rdmrocha Hi and thanks for taking the time to submit this pull request.

Did you know that you can find out about all of these events without the need for a delegate? Check out the Example Project, and see the view appeared/disappeared events for the menu. If you put any animations in viewWillAppear/viewWillDisappear methods, they will animate alongside the transition.

I'm inclined to keep this existing behavior instead of adding a delegate, because the delegate would be for a singleton meaning it needs to be swapped all the time.

Please let me know your thoughts and we can reopen if necessary.

**Comment by rdmrocha** [comment]
Hi @jonkykong 
My main purpose was to animate alpha or something like that based on the percentage of the opened menu. Since we cannot seem to tap into UIViewControllerAnimatedTransitioning percentage as soon as it starts to animate (like we can do in Android and have a delegate to fire and event at each progress key), my idea was to estimate the animation base on current percentage and calculated duration to make any other view aware of the rough timings to finish its own animation.
For instance, animating and hamburger style menu icon into an 'X' or blur the view controller as we pan-drag it from the edge.

If you have any solutions on how to do this, please do let me know. Thanks.

**Comment by jonkykong** [comment]
@rdmrocha see my prior comment. If you put an animation block inside of viewDidAppear/viewDidDisappear for the same duration as the menu's animation, you should see those changes happen at the same percentage. Does this accomplish what you're looking for?

**Comment by rdmrocha** [comment]
@jonkykong unfortunately not. I'm doing a custom animation to a custom hamburger icon. as I drag the drawer out, I'm aiming to mutate the icon into a cross. for that, I need the exact percentage at each key of the animation in order for them to be completely in sync. Not sure how I can solve this. But thanks for your interest

**Comment by jonkykong** [comment]
@rdmrocha if the animation durations of the menu and your icon change are the same duration and you place your icon change inside of the menu's `viewWillAppear` method they should be in sync.

**Comment by sil3r** [comment]
Hi, I have found why delegates methods could be usefull. I was working to animate an HamburgerButton when sidemenu is open, I've added the animations block into `viewWillAppear` and `viewWillDisappear` BUT it don't works... After some investigations, that's due because, `viewWillAppear` is called again after viewDidDisappear:

>    override open func viewDidDisappear(_ animated: Bool) {
>        super.viewDidDisappear(animated)
>         // Hack: force selection to get cleared on UITableViewControllers when reappearing using custom transitions
>         visibleViewController?.viewWillAppear(false)
>    }

For now, I've patched the problem by commenting this line and clearing selection myself into `didSelectRowAt` function.

**Comment by jonkykong** [comment]
@sil3r are you saying that your animation is triggered twice because of this? Did you consider using the `animated` flag to dictate whether or not you should animate the hamburger?

**Comment by tooolbox** [comment]
@jonkykong I'm doing as you say and using the `viewWillAppear` and `viewWillDisappear` methods but running into a [strange problem](https://stackoverflow.com/q/48739067/700471).  Any input you have would be appreciated.

**Comment by jonkykong** [comment]
Delegate methods now exist per the README. Please attempt that to resolve your issues.

**Comment by tooolbox** [comment]
Thanks!  You're totally right, I'm sorry for not checking the README more thoroughly.  (There is a lot there, though.)

I excised my custom delegate stuff and used your stock delegate methods, but I'm experiencing the same thing.

Of note is that when I drag from off-screen, the *first time*, the animation curve is linear.  But subsequent gesture-initiated transitions have coordinated animations on the EaseInOut curve.

**Comment by jonkykong** [comment]
Thank you for doing your research.

SideMenuTransition.swift:516 dictates the animation curve used based on whether or not the transition is interactive. If your animations are being triggered through that code path, then the buck stops there with SideMenu being buggy. There are some issues with the implementation of interactive transitions across iOS versions; it may be possible you've stumbled into another one if you don't have a bug elsewhere.

**Pull request closed without merging**
