### PR TITLE
Multiple support of Swift versions (4.2 and lower)

### PR DESCRIPTION
**Pull request by MSavisko**
Added:
Different swift versions support (4.2 and lower) via compile flag checker (for source and example).

### CODE REVIEW

**Comment by jdriselvato** [comment]
So what happens if the owner never adds these?

**Comment by MSavisko** [comment]
@jdriselvato 
Use my fork :) 

1. Replace with the new line in Podfile and save.
`pod 'SideMenu', :git => 'https://github.com/MSavisko/SideMenu.git', :branch => 'feature/swift_4.2_support' #4.2 support`

2. Then run `pod update SideMenu`

**Comment by jonkykong** [comment]
Use 5.0.1.

**Comment by iSkelzor** [comment]
Doesn't work with 5.0.1, too - same errors.

**Comment by 22Round** [comment]
@jonkykong I can confirm, version 5.0.1 works as expected

**Comment by tonespy** [comment]
> Doesn't work with 5.0.1, too - same errors.

@iSkelzor the deployment target of your project needs to be 10.0 to build.

**Pull request merged**
