### PR TITLE
Adding Carthage support

### PR DESCRIPTION
**Pull request by soheilbm**

### CODE REVIEW

**Comment by jonkykong** [comment]
Hello @soheilbm,

Thanks for contributing. Is it necessary for SideMenu-Example.xcscheme to be removed? Preserving it makes it easier for me to verify bugs and submit updates to Cocoapods when needed.

That said, the other xcschemes are likely not necessary.

**Comment by jonkykong** [comment]
@soheilbm thoughts?

**Comment by soheilbm** [comment]
@jonkykong I would suggest to remove the SideMenu-Example and add it into the SideMenu.xcworkspace as a separate target just for testing the cocoapods.

**Comment by jonkykong** [comment]
@soheilbm I'm failing to see improvement in moving the example... is this sparing Carthage from importing unnecessary project files?

If so, in the process of moving the example project, you omitted some files (like the launch screen) which makes the simulator experience not support larger phone screen resolutions which is undesirable. I'd like to ensure everything is free of any Xcode warnings for credibility. Additionally, the pod files have been added twice (in each project, the example and the pod) which isn't needed and is confusing.

**Comment by soheilbm** [comment]
@jonkykong My apology for removing the launch screen. I added back in my last commit.

**Pull request merged**
