### PR TITLE
Double sided side menu

### PR DESCRIPTION
**Pull request by rrpinc**

### CODE REVIEW

**Comment by ilandbt** [comment]
@rrpinc , is this PR going to be accepted?

**Comment by jonkykong** [comment]
@ilandbt: @rrpinc closed this so I have not reviewed it. If your interest is in individual settings for each SideMenu, simply change those settings in your subclasses before the menu presents for the desired effect. As currently designed it meets most people's needs so I am not inclined to take on the complexity of separate settings for each menu.

**Comment by rrpinc** [comment]
@jonkykong , @ilandbt , I closed the PR as it was unintentionally opened for review too early on my end.
@jonkykong , will you be willing to consider a different setup in which the default setup is having a 
'one config to rule them all' and a way to get a two sided config as well?

**Comment by jonkykong** [comment]
@rrpinc I never say never. It might be beneficial for us to discuss what this design would be like before you take the time implementing it, just in case. I'd also be interested to know why you're interested in having side menus behave different from a design standpoint.

**Comment by rrpinc** [comment]
@jonkykong , regarding the design standpoint: I may wish to incorporate different context & features in either menu, hence, may  want to give it a different look and feel.
I can share examples from the industry like Slack who do it as well, where the left menu holds Messaging info whereas the right one holds the user's profile.

**Pull request closed without merging**
