### PR TITLE
Added transition delegate with main events.

### PR DESCRIPTION
**Pull request by sherm4n90**
Added `menuTransitionDelegate` property to the `SideMenuManager`  class.
The delegate can implement optionally methods from the `SideMenuTransitionDelegate` protocol.

### CODE REVIEW

**Comment by jonkykong** [comment]
Hi @sherm4n90,

First, thanks for taking the time to make this contribution to SideMenu!

Out of curiosity: given that the repo uses custom transitions, it's possible to capture these same events using viewWillAppear, viewDidDisappear, etc.. Is there a specific reason you think this delegate is necessary beyond that?

**Comment by sherm4n90** [comment]
Hi @jonkykong, I noticed that some UI changes are not made until the transition already started. Maybe  `menuWillShow:`,  `menuDidShow:`, `menuWillHide:` and `menuDidHide:` are possible to detect with the normal `UIViewController` life cycle as you said, but specifically the pan gesture I could not find a way to detect it with those methods. I was trying to dismiss the keyboard before the transition started that is why I need it in first place.

**Comment by jonkykong** [comment]
@sherm4n90 I see, that's an interesting scenario. So `viewWillDisappear` isn't soon enough to dismiss the keyboard before the menu starts to appear? What happens?

**Comment by sherm4n90** [comment]
@jonkykong Exactly, the presenting VC's `viewWillDisappear` nor the menu's `viewWillAppear` will accurately detect the pan gesture. I was having weird keyboard effects in some cases and also when I came back the focus was restored which leads me to other problems. This way I solved it, so I thought it was good to include it.

**Comment by jonkykong** [comment]
@sherm4n90 thanks a lot for explaining! I had been avoiding the need for a delegate solution for a long time in favor of using the existing methods, but you've articulated a scenario where it isn't enough. I will have to try this out for myself to see what happens - my guess is the keyboard is animating its appearance/disappearance with the transition, which IMO seems like a bug on Apple's side.

One last question: did you consider adding your own gesture similar to SideMenu to dismiss the keyboard? Or inserting `self.view.endEditing(true)` anywhere in your subclass of `UISideMenuNavigationController`?

**Comment by sherm4n90** [comment]
That's what I supposed too, UIKit may be animating all things together. I tried both, `self.view.endEditing(true)` | `self.textField.resignsFirstResponder()` and also adding a gesture in my main view to detect it first, but that would prevent the menu from work. If you have any other ideas let me know and I will try. Thanks.

**Comment by jonkykong** [comment]
@sherm4n90 I was able to resolve this my placing `presentingViewController?.view.endEditing(true)` in the `viewWillAppear` event of `UISideMenuNavigationController`. The latest version of SideMenu includes this fix.

I am closing this PR resolved. If you find that there's still a problem, let me know and we can consider reopening this PR.

**Comment by glm4** [comment]
@jonkykong Hi man, just to let you know that the fix in the latest version does not solve my issue. I recently updated to swift 3 and I have the same problem. Just to be clear it is not just weird keyboard animations, it is also a black space when the dismissing the menu after presenting it with the keyboard open.

**Comment by jonkykong** [comment]
@glm4 You'll have to provide screenshots or video to properly demonstrate the issue.

**Comment by glm4** [comment]
@jonkykong Ok, I will try to send you a demo project reproducing the issue. Thanks

**Comment by cowboyrushforth** [comment]
Having the same issue.

@glm4 in your delegate, how do you make the call to endEditing?  Do you set the delegate on the controller that is presented?  Do you only have 1 menu?  Using your branch now, and curious where you listen/delegate from.

**Comment by glm4** [comment]
@cowboyrushforth I have only the left menu active, when I set the delegate when I set the menuLeftViewController and all the other configuration for the SideMenuManager singleton. Then I call
```
 func panGestureStarted(from direction: UIRectEdge) {
    myField.resignFirstResponder()
  }
```

I guess endEditing should work too.

**Pull request closed without merging**
