### PR TITLE
Configuration to Carthage Support

### PR DESCRIPTION
**Pull request by andre991**
Hi, I've made some changes in SideMenu to become compatible with Carthage.

### CODE REVIEW

**Comment by juegas** [comment]
👍  this is working for me

**Comment by sebbean** [comment]
would help me as well. :-)

**Comment by jonkykong** [comment]
Thanks @andre991 for making the corrections and @juegas and @sebbean for confirming. I'm sorry I haven't gotten to this yet, I'm focusing on other project work at the moment but I promise I'll get to it soon.

**Comment by sebbean** [comment]
FYI the only change I needed for carthage was the checkbox on the right

screen shot 2016-11-29 at 3 07 56 pm

**Comment by sebbean** [comment]
ignore that last comment it built in carthage. Project didnt build though.

**Comment by VipulAdglobal** [comment]
I used side menu in my app. But i want to dismiss left menu manual to click on one of the menu item. 
I used this code to dismiss left menu SideMenuManager.menuLeftNavigationController?.dismiss(animated: true, completion: nil)

left menu not dismiss on single click. it is dismiss on double click.

**Comment by leoneparise** [comment]
👍  To merge this. =)

**Pull request merged**
